<?php
return [
    [
        'title' => 'Luxury Mansion with Garden',
        'slug' => 'luxury-mansion-garden',
        'cover_image' => 'https://a0.muscache.com/im/pictures/40706270/81c0585d_original.jpg?im_w=1440&im_q=highq',
        'description' => 'A luxurious mansion with a sprawling garden and exquisite interior design.',
        'num_rooms' => 8,
        'num_beds' => 8,
        'num_baths' => 4,
        'mq' => 350,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via del Corso, 10',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 1280.75,
        'type' => 'mansion',
        'floor' => 2,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Modern City Apartment',
        'slug' => 'modern-city-apartment',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6OTc4Njc2MjY4MzQ3Mjg2MjI5/original/e9bbe93b-8052-4f9e-848e-34a1c809dcb9.jpeg?im_w=960',
        'description' => 'A modern city apartment, fully furnished and close to public transport.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 2,
        'mq' => 90,
        'zip' => '20121',
        'city' => 'Milan',
        'address' => 'Corso Vittorio Emanuele, 15',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 850.50,
        'type' => 'apartment',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Lakefront Property with Dock',
        'slug' => 'lakefront-property-dock',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MzY2NTI2NDQ%3D/original/5f063293-c7de-48d2-8f06-010fa49dba71.jpeg?im_w=1440&im_q=highq',
        'description' => 'A beautiful lakefront property with stunning water views and private dock.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 150,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Via Toledo, 22',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 800.20,
        'type' => 'lake',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Luxurious Garden Mansion',
        'slug' => 'luxurious-garden-mansion',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-715732504820084395/original/2ae31e54-fbfb-487c-841f-62908db2539e.jpeg?im_w=1440&im_q=highq',
        'description' => 'A luxurious mansion with a sprawling garden and exquisite interior design.',
        'num_rooms' => 7,
        'num_beds' => 7,
        'num_baths' => 3,
        'mq' => 300,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via del Corso, 11',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 1250.75,
        'type' => 'mansion',
        'floor' => 2,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Ski Lodge with Slope Access',
        'slug' => 'ski-lodge-slope-access',
        'cover_image' => 'https://a0.muscache.com/im/pictures/97df6bb0-c927-45ed-a4da-ebf75cd3a28f.jpg?im_w=960',
        'description' => 'A cozy ski lodge with direct access to the slopes, perfect for winter sports enthusiasts.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 120,
        'zip' => '20121',
        'city' => 'Milan',
        'address' => 'Corso Vittorio Emanuele, 16',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 540.60,
        'type' => 'ski-in/out',
        'floor' => 1,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Nature Treehouse Getaway',
        'slug' => 'nature-treehouse-getaway',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-852570601015025177/original/64890f13-26cf-4cb5-978a-b64e9fe7e5f9.jpeg?im_w=1440&im_q=highq',
        'description' => 'A unique treehouse surrounded by nature, offering a tranquil getaway experience.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 35,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Via Toledo, 23',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 250.30,
        'type' => 'tree-house',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Stylish City Apartment',
        'slug' => 'stylish-city-apartment',
        'cover_image' => 'https://a0.muscache.com/im/pictures/d45bcb02-cc52-43e0-bf5e-73c0b90e7f94.jpg?im_w=1440&im_q=highq',
        'description' => 'A modern city apartment, fully furnished and close to public transport.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 2,
        'mq' => 85,
        'zip' => '50122',
        'city' => 'Florence',
        'address' => 'Piazza del Duomo, 5',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 830.45,
        'type' => 'apartment',
        'floor' => 3,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Panoramic Geodesic Dome',
        'slug' => 'panoramic-geodesic-dome',
        'cover_image' => 'https://a0.muscache.com/im/pictures/27716585/6ae34f42_original.jpg?im_w=1440&im_q=highq',
        'description' => 'A geodesic dome with large windows, providing a panoramic view of the countryside.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 55,
        'zip' => '30124',
        'city' => 'Venice',
        'address' => 'Piazza San Marco, 9',
        'lat' => '45.434046',
        'long' => '12.338784',
        'price' => 400.90,
        'type' => 'dome',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Rustic Cave Dwelling',
        'slug' => 'rustic-cave-dwelling',
        'cover_image' => 'https://a0.muscache.com/im/pictures/41872e64-a8b6-4c66-a7de-5c83e8c4a250.jpg?im_w=1440&im_q=highq',
        'description' => 'A converted cave dwelling with a rustic charm and modern amenities.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 45,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via del Corso, 13',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 210.50,
        'type' => 'cave',
        'floor' => 0,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Mountain Forest Cabin',
        'slug' => 'mountain-forest-cabin',
        'cover_image' => 'https://a0.muscache.com/im/pictures/41872e64-a8b6-4c66-a7de-5c83e8c4a250.jpg?im_w=1440&im_q=highq',
        'description' => 'A cozy cabin in the mountains, ideal for a peaceful retreat surrounded by forest.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 70,
        'zip' => '20121',
        'city' => 'Milan',
        'address' => 'Corso Vittorio Emanuele, 17',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 320.75,
        'type' => 'cabin',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1

    ],
    [
        'title' => 'Waterfront Lake Villa',
        'slug' => 'waterfront-lake-villa',
        'cover_image' => 'https://a0.muscache.com/im/pictures/2385c7cd-4d7b-411a-8093-db3b79f3f66d.jpg?im_w=720',
        'description' => 'A beautiful lakefront property with stunning water views and private dock.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 150,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Via Caracciolo, 25',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 780.40,
        'type' => 'lake',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Seaside Beachfront Villa',
        'slug' => 'seaside-beachfront-villa',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MzExODU2NjM%3D/original/d2a650e6-3386-45f5-a6b4-e5fb7a2449aa.jpeg?im_w=720',
        'description' => 'A beachfront villa with direct access to the sandy shores, perfect for summer holidays.',
        'num_rooms' => 6,
        'num_beds' => 6,
        'num_baths' => 3,
        'mq' => 220,
        'zip' => '50122',
        'city' => 'Florence',
        'address' => 'Lungarno Vespucci, 12',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 1230.60,
        'type' => 'beach',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Ancient Venetian Castle',
        'slug' => 'ancient-venetian-castle',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-6919592/original/40658605-0b96-46ea-b88b-707c3aac316f.jpeg?im_w=720',
        'description' => 'An ancient castle with historical architecture, ideal for hosting grand events.',
        'num_rooms' => 15,
        'num_beds' => 15,
        'num_baths' => 6,
        'mq' => 750,
        'zip' => '30124',
        'city' => 'Venice',
        'address' => 'Campo San Polo, 3',
        'lat' => '45.434046',
        'long' => '12.338784',
        'price' => 1450.90,
        'type' => 'castle',
        'floor' => 1,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Garden Mansion in Rome',
        'slug' => 'garden-mansion-rome',
        'cover_image' => 'https://a0.muscache.com/im/pictures/5e14c015-abe6-4305-87d5-95511fe1a6fe.jpg?im_w=720',
        'description' => 'A luxurious mansion with a sprawling garden and exquisite interior design.',
        'num_rooms' => 8,
        'num_beds' => 8,
        'num_baths' => 4,
        'mq' => 340,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via Appia Antica, 45',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 1280.55,
        'type' => 'mansion',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Mountain Chalet Lodge',
        'slug' => 'mountain-chalet-lodge',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-801341623720043983/original/2297c033-f03e-4f6a-97dc-86316e924859.jpeg?im_w=720',
        'description' => 'A cozy ski lodge with direct access to the slopes, perfect for winter sports enthusiasts.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 2,
        'mq' => 100,
        'zip' => '20121',
        'city' => 'Turin',
        'address' => 'Via Roma, 18',
        'lat' => '45.070312',
        'long' => '7.686856',
        'price' => 570.30,
        'type' => 'ski-in/out',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Forest Treehouse Retreat',
        'slug' => 'forest-treehouse-retreat',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-48911981/original/486eb8a5-977c-4e98-8fde-d8566347eb57.jpeg?im_w=1440&im_q=highq',
        'description' => 'A unique treehouse surrounded by nature, offering a tranquil getaway experience.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 30,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Via Posillipo, 29',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 270.50,
        'type' => 'tree-house',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Central Florence Apartment',
        'slug' => 'central-florence-apartment',
        'cover_image' => 'https://a0.muscache.com/im/pictures/650c2e2e-8d20-46f9-94de-eae8020d351c.jpg?im_w=720',
        'description' => 'A modern city apartment, fully furnished and close to public transport.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 90,
        'zip' => '50122',
        'city' => 'Florence',
        'address' => 'Piazza della Repubblica, 4',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 845.75,
        'type' => 'apartment',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Geodesic Dome Home',
        'slug' => 'geodesic-dome-home',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-675949174523622927/original/462b2652-01aa-4bc4-b0e3-b2c388fa6bd9.jpeg?im_w=720',
        'description' => 'A geodesic dome with large windows, providing a panoramic view of the countryside.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 40,
        'zip' => '30124',
        'city' => 'Venice',
        'address' => 'Fondamenta San Giobbe, 6',
        'lat' => '45.434046',
        'long' => '12.338784',
        'price' => 410.80,
        'type' => 'dome',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Traditional Cave House',
        'slug' => 'traditional-cave-house',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-48897348/original/b635f956-a2cb-4386-b514-5dabba8bc755.jpeg?im_w=720',
        'description' => 'A converted cave dwelling with a rustic charm and modern amenities.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 50,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via dei Fori Imperiali, 14',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 220.10,
        'type' => 'cave',
        'floor' => 0,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Secluded Forest Cabin',
        'slug' => 'secluded-forest-cabin',
        'cover_image' => 'https://a0.muscache.com/im/pictures/898fe366-80f6-4773-800c-dc30f3e91dd5.jpg?im_w=720',
        'description' => 'A cozy cabin in the mountains, ideal for a peaceful retreat surrounded by forest.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 75,
        'zip' => '20121',
        'city' => 'Milan',
        'address' => 'Via Montenapoleone, 8',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 330.20,
        'type' => 'cabin',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Lakefront Villa with Dock',
        'slug' => 'lakefront-villa-dock',
        'cover_image' => 'https://a0.muscache.com/im/pictures/airflow/Hosting-573795977090488084/original/9cb82835-24d4-47d7-9813-d41981c39727.jpg?im_w=720',
        'description' => 'A beautiful lakefront property with stunning water views and private dock.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 150,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Via Caracciolo, 25',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 780.40,
        'type' => 'lake',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Exclusive Beach Villa',
        'slug' => 'exclusive-beach-villa',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-949295652607639713/original/b4ced034-7611-4732-93a6-74ce16b74f54.jpeg?im_w=720',
        'description' => 'A beachfront villa with direct access to the sandy shores, perfect for summer holidays.',
        'num_rooms' => 6,
        'num_beds' => 6,
        'num_baths' => 3,
        'mq' => 220,
        'zip' => '50122',
        'city' => 'Florence',
        'address' => 'Lungarno Vespucci, 12',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 1230.60,
        'type' => 'beach',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Historic Venetian Castle',
        'slug' => 'historic-venetian-castle',
        'cover_image' => 'https://a0.muscache.com/im/pictures/8e94d0f0-8660-425e-8007-c32672b06a65.jpg?im_w=720',
        'description' => 'An ancient castle with historical architecture, ideal for hosting grand events.',
        'num_rooms' => 15,
        'num_beds' => 15,
        'num_baths' => 6,
        'mq' => 750,
        'zip' => '30124',
        'city' => 'Venice',
        'address' => 'Campo San Polo, 3',
        'lat' => '45.434046',
        'long' => '12.338784',
        'price' => 1450.90,
        'type' => 'castle',
        'floor' => 1,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Spacious Garden Mansion',
        'slug' => 'spacious-garden-mansion',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-24282987/original/a3961b48-6071-4d98-be0f-f176f39824db.jpeg?im_w=720',
        'description' => 'A luxurious mansion with a sprawling garden and exquisite interior design.',
        'num_rooms' => 8,
        'num_beds' => 8,
        'num_baths' => 4,
        'mq' => 340,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via Appia Antica, 45',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 1280.55,
        'type' => 'mansion',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Charming Ski Chalet',
        'slug' => 'charming-ski-chalet',
        'cover_image' => 'https://a0.muscache.com/im/pictures/8d8eebcf-bc98-4189-9d25-18287954a89e.jpg?im_w=720',
        'description' => 'A cozy ski lodge with direct access to the slopes, perfect for winter sports enthusiasts.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 2,
        'mq' => 100,
        'zip' => '20121',
        'city' => 'Turin',
        'address' => 'Via Roma, 18',
        'lat' => '45.070312',
        'long' => '7.686856',
        'price' => 570.30,
        'type' => 'ski-in/out',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Serene Forest Treehouse',
        'slug' => 'serene-forest-treehouse',
        'cover_image' => 'https://a0.muscache.com/im/pictures/898fe366-80f6-4773-800c-dc30f3e91dd5.jpg?im_w=720',
        'description' => 'A unique treehouse surrounded by nature, offering a tranquil getaway experience.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 30,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Via Posillipo, 29',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 270.50,
        'type' => 'tree-house',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Luxury Apartment Florence',
        'slug' => 'luxury-apartment-florence',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-691869876520105705/original/be26495a-c0ca-4f33-8ded-3807aa332209.jpeg?im_w=1440&im_q=highq',
        'description' => 'A modern city apartment, fully furnished and close to public transport.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 90,
        'zip' => '50122',
        'city' => 'Florence',
        'address' => 'Piazza della Repubblica, 4',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 845.75,
        'type' => 'apartment',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Countryside Dome Retreat',
        'slug' => 'countryside-dome-retreat',
        'cover_image' => 'https://a0.muscache.com/im/pictures/ec457b46-5f78-43a2-ae42-e6c3bdfbe6c5.jpg?im_w=720',
        'description' => 'A geodesic dome with large windows, providing a panoramic view of the countryside.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 40,
        'zip' => '30124',
        'city' => 'Venice',
        'address' => 'Fondamenta San Giobbe, 6',
        'lat' => '45.434046',
        'long' => '12.338784',
        'price' => 410.80,
        'type' => 'dome',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Authentic Cave Home',
        'slug' => 'authentic-cave-home',
        'cover_image' => 'https://a0.muscache.com/im/pictures/5de70d97-b567-4957-85f3-e609fb6d8f6a.jpg?im_w=1440&im_q=highq',
        'description' => 'A converted cave dwelling with a rustic charm and modern amenities.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 50,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via dei Fori Imperiali, 14',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 220.10,
        'type' => 'cave',
        'floor' => 0,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Quiet Forest Cabin',
        'slug' => 'quiet-forest-cabin',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-663628334676790509/original/6bb86806-c377-41b5-a8d3-de0bfb153b3a.jpeg?im_w=720',
        'description' => 'A cozy cabin in the mountains, ideal for a peaceful retreat surrounded by forest.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 75,
        'zip' => '20121',
        'city' => 'Milan',
        'address' => 'Via Montenapoleone, 8',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 330.20,
        'type' => 'cabin',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Lakeside Residence',
        'slug' => 'lakeside-residence',
        'cover_image' => 'https://a0.muscache.com/im/pictures/08774368-330f-4154-8a53-560bae335b72.jpg?im_w=720',
        'description' => 'A beautiful lakefront property with stunning water views and private dock.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 160,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Viale Virgilio, 14',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 800.40,
        'type' => 'lake',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Beachside Family Villa',
        'slug' => 'beachside-family-villa',
        'cover_image' => 'https://a0.muscache.com/im/pictures/a983ae03-d09c-4efa-ad27-deeac242ea01.jpg?im_w=720',
        'description' => 'A beachfront villa with direct access to the sandy shores, perfect for summer holidays.',
        'num_rooms' => 5,
        'num_beds' => 5,
        'num_baths' => 3,
        'mq' => 200,
        'zip' => '50122',
        'city' => 'Florence',
        'address' => 'Viale Michelangelo, 27',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 1200.75,
        'type' => 'beach',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Historical Castle Retreat',
        'slug' => 'historical-castle-retreat',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-846191369608841971/original/2d7b26e4-b111-4e53-9724-4a4449761d53.jpeg?im_w=720',
        'description' => 'An ancient castle with historical architecture, ideal for hosting grand events.',
        'num_rooms' => 12,
        'num_beds' => 12,
        'num_baths' => 5,
        'mq' => 700,
        'zip' => '30124',
        'city' => 'Venice',
        'address' => 'Calle Larga, 11',
        'lat' => '45.434046',
        'long' => '12.338784',
        'price' => 1400.60,
        'type' => 'castle',
        'floor' => 1,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Grand Rome Mansion',
        'slug' => 'grand-rome-mansion',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-69439/original/4ec0ebad-377b-436e-bbd6-aca5aeaacbc4.jpeg?im_w=720',
        'description' => 'A luxurious mansion with a sprawling garden and exquisite interior design.',
        'num_rooms' => 9,
        'num_beds' => 9,
        'num_baths' => 5,
        'mq' => 450,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via Giulia, 32',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 1350.75,
        'type' => 'mansion',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Ski Lodge in Alps',
        'slug' => 'ski-lodge-alps',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-1045854960701532360/original/862245f6-4040-4ae2-ab39-87a008084da5.jpeg?im_w=720',
        'description' => 'A cozy ski lodge with direct access to the slopes, perfect for winter sports enthusiasts.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 1,
        'mq' => 110,
        'zip' => '20121',
        'city' => 'Milan',
        'address' => 'Via Bagutta, 19',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 560.90,
        'type' => 'ski-in/out',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Rustic Treehouse Hideaway',
        'slug' => 'rustic-treehouse-hideaway',
        'cover_image' => 'https://a0.muscache.com/im/pictures/03d1a59c-672d-4c10-80ec-3dce231fc643.jpg?im_w=720',
        'description' => 'A unique treehouse surrounded by nature, offering a tranquil getaway experience.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 25,
        'zip' => '80132',
        'city' => 'Naples',
        'address' => 'Via Partenope, 21',
        'lat' => '40.851775',
        'long' => '14.268124',
        'price' => 260.25,
        'type' => 'tree-house',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Elegant Florence Apartment',
        'slug' => 'elegant-florence-apartment',
        'cover_image' => 'https://a0.muscache.com/im/pictures/e7b895af-bb32-4fb8-9cd8-7f0885645c0c.jpg?im_w=720',
        'description' => 'A modern city apartment, fully furnished and close to public transport.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 2,
        'mq' => 95,
        'zip' => '50122',
        'city' => 'Florence',
        'address' => 'Borgo San Frediano, 14',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 855.40,
        'type' => 'apartment',
        'floor' => 2,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Dome Home Countryside View',
        'slug' => 'dome-home-countryside',
        'cover_image' => 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-945451930446865365/original/20589ea0-db51-4921-8ef4-12327c2bad4e.jpeg?im_w=720',
        'description' => 'A geodesic dome with large windows, providing a panoramic view of the countryside.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 45,
        'zip' => '30124',
        'city' => 'Venice',
        'address' => 'Sestiere Dorsoduro, 44',
        'lat' => '45.434046',
        'long' => '12.338784',
        'price' => 420.55,
        'type' => 'dome',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Urban Cave Residence',
        'slug' => 'urban-cave-residence',
        'cover_image' => 'https://a0.muscache.com/im/pictures/7eeb13ed-82da-4432-ba43-813438ce215e.jpg?im_w=720',
        'description' => 'A converted cave dwelling with a rustic charm and modern amenities.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 35,
        'zip' => '00184',
        'city' => 'Rome',
        'address' => 'Via dei Cappuccini, 7',
        'lat' => '41.9027835',
        'long' => '12.4963655',
        'price' => 225.75,
        'type' => 'cave',
        'floor' => 0,
        'available' => false,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Woodland Mountain Cabin',
        'slug' => 'woodland-mountain-cabin',
        'cover_image' => 'https://a0.muscache.com/im/pictures/eb7e8183-50a2-4495-9d9c-9c775b98d0fe.jpg?im_w=720',
        'description' => 'A cozy cabin in the mountains, ideal for a peaceful retreat surrounded by forest.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 80,
        'zip' => '20121',
        'city' => 'Milan',
        'address' => 'Via Monte Rosa, 2',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 335.20,
        'type' => 'cabin',
        'floor' => 1,
        'available' => true,
        'sponsored' => true,
        'user_id' => 1
    ],
];
