<?php
return [
    [
        'title' => 'Modern City Studio',
        'slug' => 'modern-city-studio',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6OTc4Njc2MjY4MzQ3Mjg2MjI5/original/e9bbe93b-8052-4f9e-848e-34a1c809dcb9.jpeg?im_w=960',
        'images' => [
            'https://a0.muscache.com/im/pictures/20022381/09236f79_original.jpg?im_w=720',
            'https://a0.muscache.com/im/pictures/20022548/36f71be6_original.jpg?im_w=720',
            'https://a0.muscache.com/im/pictures/20022856/21e8c7a0_original.jpg?im_w=1200',
            'https://a0.muscache.com/im/pictures/20022895/33c50f88_original.jpg?im_w=720',
            'https://a0.muscache.com/im/pictures/20022919/fed0604c_original.jpg?im_w=720',
        ],
        'description' => 'A stylish, compact studio apartment in the heart of the city, ideal for solo travelers.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 40,
        'address' => 'Via Torino, 6, 10121 Turin',
        'lat' => '45.070312',
        'long' => '7.686856',
        'price' => 680.50,
        'type' => 'apartment',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Rustic Lakeside Cabin',
        'slug' => 'rustic-lakeside-cabin',
        'cover_image' => 'https://a0.muscache.com/im/pictures/41872e64-a8b6-4c66-a7de-5c83e8c4a250.jpg?im_w=1440&im_q=highq',
        'description' => 'A cozy cabin by the lake, offering tranquil views and nature trails.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 50,
        'address' => 'Lago di Vico, 8, 01037 Ronciglione',
        'lat' => '42.328169',
        'long' => '12.215233',
        'price' => 300.00,
        'type' => 'cabin',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Luxury Penthouse with Cityscape',
        'slug' => 'luxury-penthouse-cityscape',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-691869876520105705/original/be26495a-c0ca-4f33-8ded-3807aa332209.jpeg?im_w=1440&im_q=highq',
        'description' => 'A high-rise penthouse offering a stunning cityscape and luxurious amenities.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 3,
        'mq' => 200,
        'address' => 'Viale Monte Grappa, 10, 20124 Milan',
        'lat' => '45.478644',
        'long' => '9.20672',
        'price' => 2300.75,
        'type' => 'apartment',
        'floor' => 12,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'Ski Lodge with Mountain View',
        'slug' => 'ski-lodge-mountain-view',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-1045854960701532360/original/862245f6-4040-4ae2-ab39-87a008084da5.jpeg?im_w=720',
        'description' => 'A rustic ski lodge with direct access to the slopes and beautiful mountain views.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 100,
        'address' => 'Strada dello Stelvio, 4, 23032 Bormio',
        'lat' => '46.468972',
        'long' => '10.367942',
        'price' => 525.50,
        'type' => 'ski-in/out',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Exclusive Treehouse with Ocean View',
        'slug' => 'exclusive-treehouse-ocean-view',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-852570601015025177/original/64890f13-26cf-4cb5-978a-b64e9fe7e5f9.jpeg?im_w=1440&im_q=highq',
        'description' => 'An elevated treehouse with breathtaking views of the ocean and surrounding forest.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 30,
        'address' => 'Bosco Marino, 12, 97014 Ispica',
        'lat' => '36.784223',
        'long' => '14.898564',
        'price' => 275.75,
        'type' => 'tree-house',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Classic Italian Villa with Garden',
        'slug' => 'classic-italian-villa-garden',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-23015320/original/a768bb26-aba3-4898-88f3-72d82d497089.jpeg?im_w=1200',
        'description' => 'A beautiful villa with a lush garden, situated in the Tuscan countryside.',
        'num_rooms' => 5,
        'num_beds' => 5,
        'num_baths' => 3,
        'mq' => 220,
        'address' => 'Via del Chianti, 23, 53013 Gaiole in Chianti',
        'lat' => '43.469456',
        'long' => '11.383899',
        'price' => 1675.45,
        'type' => 'mansion',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Panoramic Dome Retreat',
        'slug' => 'panoramic-dome-retreat',
        'cover_image' => 'https://a0.muscache.com/im/pictures/27716585/6ae34f42_original.jpg?im_w=1440&im_q=highq',
        'description' => 'A modern dome structure with panoramic views of rolling hills and vineyards.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 40,
        'address' => 'Colline Toscane, 15, 56048 Volterra',
        'lat' => '43.402779',
        'long' => '10.861389',
        'price' => 410.35,
        'type' => 'dome',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'Historic Countryside Castle',
        'slug' => 'historic-countryside-castle',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-6919592/original/40658605-0b96-46ea-b88b-707c3aac316f.jpeg?im_w=720',
        'description' => 'A majestic castle with rich history, surrounded by scenic countryside.',
        'num_rooms' => 15,
        'num_beds' => 15,
        'num_baths' => 6,
        'mq' => 700,
        'address' => 'Castello di Sorano, 1, 58010 Sorano',
        'lat' => '42.682915',
        'long' => '11.721264',
        'price' => 1450.90,
        'type' => 'castle',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Countryside Vineyard Villa',
        'slug' => 'countryside-vineyard-villa',
        'cover_image' => 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-802785519039957337/original/1650faae-cddc-4f9b-a250-d4d7d1609bd0.jpeg?im_w=1200',
        'description' => 'A charming villa surrounded by vineyards, perfect for wine enthusiasts.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 2,
        'mq' => 180,
        'address' => 'Via delle Vigne, 10, 53024 Montalcino',
        'lat' => '43.054071',
        'long' => '11.486846',
        'price' => 1250.65,
        'type' => 'mansion',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Seaside Beach Bungalow',
        'slug' => 'seaside-beach-bungalow',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-949295652607639713/original/b4ced034-7611-4732-93a6-74ce16b74f54.jpeg?im_w=720',
        'description' => 'A cozy beach bungalow with direct access to the sandy shores.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 65,
        'address' => 'Via del Mare, 18, 91023 Favignana',
        'lat' => '37.925607',
        'long' => '12.329746',
        'price' => 710.30,
        'type' => 'beach',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Alpine Treehouse Hideaway',
        'slug' => 'alpine-treehouse-hideaway',
        'cover_image' => 'https://a0.muscache.com/im/pictures/898fe366-80f6-4773-800c-dc30f3e91dd5.jpg?im_w=720',
        'description' => 'A unique treehouse nestled in an alpine forest, offering spectacular views.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 35,
        'address' => 'Bosco di San Bernardo, 5, 39030 San Lorenzo di Sebato',
        'lat' => '46.802179',
        'long' => '11.896595',
        'price' => 320.25,
        'type' => 'tree-house',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'City Penthouse with Rooftop Pool',
        'slug' => 'city-penthouse-rooftop-pool',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-48540750/original/ad68b77a-c309-4aef-87c5-d3964281cf29.jpeg?im_w=720',
        'description' => 'A luxurious penthouse with a private rooftop pool and panoramic city views.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 150,
        'address' => 'Via della Libertà, 15, 90143 Palermo',
        'lat' => '38.135125',
        'long' => '13.359763',
        'price' => 2100.90,
        'type' => 'apartment',
        'floor' => 10,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'Rustic Mountain Cabin Escape',
        'slug' => 'rustic-mountain-cabin-escape',
        'cover_image' => 'https://a0.muscache.com/im/pictures/979cdf3a-2bd0-4567-8a07-2e2eb076aeee.jpg?im_w=1200',
        'description' => 'A rustic cabin in the mountains, perfect for a serene getaway in nature.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 55,
        'address' => 'Località Prati di Gaggio, 9, 22010 Pianello del Lario',
        'lat' => '46.096667',
        'long' => '9.275278',
        'price' => 295.00,
        'type' => 'cabin',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Luxury Dome with Valley View',
        'slug' => 'luxury-dome-valley-view',
        'cover_image' => 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-945451930446865365/original/20589ea0-db51-4921-8ef4-12327c2bad4e.jpeg?im_w=720',
        'description' => 'A luxurious dome offering views over a picturesque valley, ideal for relaxation.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 45,
        'address' => 'Colle della Maddalena, 7, 70043 Monopoli',
        'lat' => '40.956004',
        'long' => '17.298199',
        'price' => 415.40,
        'type' => 'dome',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'Modern City Apartment with Balcony',
        'slug' => 'modern-city-apartment-balcony',
        'cover_image' => 'https://a0.muscache.com/im/pictures/d45bcb02-cc52-43e0-bf5e-73c0b90e7f94.jpg?im_w=1440&im_q=highq',
        'description' => 'A sleek, modern apartment in the city center with a private balcony.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 85,
        'address' => 'Corso Buenos Aires, 20, 20124 Milan',
        'lat' => '45.478644',
        'long' => '9.20672',
        'price' => 980.75,
        'type' => 'apartment',
        'floor' => 4,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Secluded Hillside Castle',
        'slug' => 'secluded-hillside-castle',
        'cover_image' => 'https://a0.muscache.com/im/pictures/8e94d0f0-8660-425e-8007-c32672b06a65.jpg?im_w=720',
        'description' => 'A historic castle on a hillside with panoramic views of the surrounding countryside.',
        'num_rooms' => 10,
        'num_beds' => 10,
        'num_baths' => 5,
        'mq' => 500,
        'address' => 'Castello di Rivoli, 1, 10098 Rivoli',
        'lat' => '45.070297',
        'long' => '7.508305',
        'price' => 1300.90,
        'type' => 'castle',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Treetop Cabin in the Dolomites',
        'slug' => 'treetop-cabin-dolomites',
        'cover_image' => 'https://a0.muscache.com/im/pictures/15cd9844-c922-4492-b0c8-caee369cde09.jpg?im_w=1200',
        'description' => 'A unique cabin set among treetops in the Dolomites, perfect for nature lovers.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 35,
        'address' => 'Località Croda da Lago, 2, 32043 Cortina d\'Ampezzo',
        'lat' => '46.541852',
        'long' => '12.135913',
        'price' => 355.00,
        'type' => 'tree-house',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Seaside Villa with Private Pool',
        'slug' => 'seaside-villa-private-pool',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-579252/original/425f2cb4-9a90-4bbc-9221-3d75be20a1bc.jpeg?im_w=1200',
        'description' => 'A spacious villa by the sea with a private pool and beach access.',
        'num_rooms' => 6,
        'num_beds' => 6,
        'num_baths' => 4,
        'mq' => 250,
        'address' => 'Viale dei Pini, 22, 09045 Quartu Sant\'Elena',
        'lat' => '39.230482',
        'long' => '9.203238',
        'price' => 1600.45,
        'type' => 'mansion',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'City Loft with Skyline View',
        'slug' => 'city-loft-skyline-view',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-800442420577699374/original/0f408be9-2373-465f-844b-028389d57d08.jpeg?im_w=1200',
        'description' => 'A modern loft with stunning views of the city skyline, perfect for urbanites.',
        'num_rooms' => 2,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 70,
        'address' => 'Via Roma, 12, 10121 Turin',
        'lat' => '45.070312',
        'long' => '7.686856',
        'price' => 910.50,
        'type' => 'apartment',
        'floor' => 7,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Mountain View Ski Lodge',
        'slug' => 'mountain-view-ski-lodge',
        'cover_image' => 'https://a0.muscache.com/im/pictures/8d8eebcf-bc98-4189-9d25-18287954a89e.jpg?im_w=720',
        'description' => 'A cozy ski lodge nestled in the mountains with direct access to ski slopes.',
        'num_rooms' => 4,
        'num_beds' => 4,
        'num_baths' => 2,
        'mq' => 120,
        'address' => 'Località Colle, 19, 12015 Limone Piemonte',
        'lat' => '44.190256',
        'long' => '7.577506',
        'price' => 700.30,
        'type' => 'ski-in/out',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Beachfront Villa Escape',
        'slug' => 'beachfront-villa-escape',
        'cover_image' => 'https://a0.muscache.com/im/pictures/a983ae03-d09c-4efa-ad27-deeac242ea01.jpg?im_w=720',
        'description' => 'A luxurious beachfront villa with breathtaking views of the sea and private beach access.',
        'num_rooms' => 5,
        'num_beds' => 5,
        'num_baths' => 3,
        'mq' => 200,
        'address' => 'Lungomare Cristoforo Colombo, 10, 90149 Palermo',
        'lat' => '38.139646',
        'long' => '13.354202',
        'price' => 1350.75,
        'type' => 'beach',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'City Center Luxury Apartment',
        'slug' => 'city-center-luxury-apartment',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-1161447484734690123/original/cbd576cc-3e2c-4318-bc28-d324fd1fdb7f.jpeg?im_w=1200',
        'description' => 'A luxury apartment located in the heart of the city, close to all amenities.',
        'num_rooms' => 3,
        'num_beds' => 3,
        'num_baths' => 2,
        'mq' => 110,
        'address' => 'Piazza della Repubblica, 6, 20121 Milan',
        'lat' => '45.464211',
        'long' => '9.191383',
        'price' => 1150.80,
        'type' => 'apartment',
        'floor' => 5,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Remote Cabin by the Lake',
        'slug' => 'remote-cabin-lake',
        'cover_image' => 'https://a0.muscache.com/im/pictures/03d2fdf8-00f4-4bec-8eee-f3d6936404ba.jpg?im_w=1200',
        'description' => 'A secluded cabin by a serene lake, perfect for a peaceful retreat.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 60,
        'address' => 'Lago di Braies, 1, 39030 Braies',
        'lat' => '46.694213',
        'long' => '12.086125',
        'price' => 280.50,
        'type' => 'cabin',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Elegant Florence Villa',
        'slug' => 'elegant-florence-villa',
        'cover_image' => 'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6OTAzMzUzMzYxNDgyNTY1NTUz/original/95cc1212-cfa9-434b-80e4-42aa4c2e548c.jpeg?im_w=1200',
        'description' => 'A beautiful villa in Florence, perfect for family holidays and gatherings.',
        'num_rooms' => 5,
        'num_beds' => 5,
        'num_baths' => 3,
        'mq' => 180,
        'address' => 'Viale Michelangelo, 27, 50122 Florence',
        'lat' => '43.769562',
        'long' => '11.255814',
        'price' => 1550.90,
        'type' => 'mansion',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Treetop Glamping Experience',
        'slug' => 'treetop-glamping-experience',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-852570601015025177/original/64890f13-26cf-4cb5-978a-b64e9fe7e5f9.jpeg?im_w=1440&im_q=highq',
        'description' => 'A luxurious treehouse with glamping facilities in the midst of nature.',
        'num_rooms' => 1,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 40,
        'address' => 'Strada del Bosco, 5, 38020 Mezzana',
        'lat' => '46.3331',
        'long' => '10.8114',
        'price' => 390.25,
        'type' => 'tree-house',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Central Penthouse with Terrace',
        'slug' => 'central-penthouse-terrace',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-48540750/original/e18cbd23-79de-417c-920c-073e0eb401ed.jpeg?im_w=1200',
        'description' => 'A luxurious penthouse with a large terrace offering panoramic city views.',
        'num_rooms' => 3,
        'num_beds' => 2,
        'num_baths' => 2,
        'mq' => 130,
        'address' => 'Via Veneto, 15, 00187 Rome',
        'lat' => '41.906349',
        'long' => '12.483312',
        'price' => 1850.00,
        'type' => 'apartment',
        'floor' => 8,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'Alpine Dome with Lake View',
        'slug' => 'alpine-dome-lake-view',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-675949174523622927/original/462b2652-01aa-4bc4-b0e3-b2c388fa6bd9.jpeg?im_w=720',
        'description' => 'A unique geodesic dome with lake views, ideal for a nature getaway.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 50,
        'address' => 'Lago di Como, 6, 23829 Varenna',
        'lat' => '46.00856',
        'long' => '9.28374',
        'price' => 415.75,
        'type' => 'dome',
        'floor' => 0,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Historic Castle Overlooking City',
        'slug' => 'historic-castle-city-view',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-846191369608841971/original/2d7b26e4-b111-4e53-9724-4a4449761d53.jpeg?im_w=720',
        'description' => 'A stunning historic castle with panoramic views of the surrounding city and countryside.',
        'num_rooms' => 12,
        'num_beds' => 12,
        'num_baths' => 5,
        'mq' => 650,
        'address' => 'Castello di Monteriggioni, 1, 53035 Monteriggioni',
        'lat' => '43.387149',
        'long' => '11.238543',
        'price' => 1425.60,
        'type' => 'castle',
        'floor' => 3,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Contemporary Loft in Milan',
        'slug' => 'contemporary-loft-milan',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-931541062888884181/original/76a49f09-c9ba-447b-acfc-d7be34b07732.jpeg?im_w=1200',
        'description' => 'A sleek and modern loft with minimalist design, perfect for business travelers.',
        'num_rooms' => 2,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 60,
        'address' => 'Corso Garibaldi, 21, 20121 Milan',
        'lat' => '45.477318',
        'long' => '9.185924',
        'price' => 1020.75,
        'type' => 'apartment',
        'floor' => 5,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'Lakefront Villa in Ronciglione',
        'slug' => 'lakefront-villa-ronciglione',
        'cover_image' => 'https://a0.muscache.com/im/pictures/7816a7c8-cf0c-4c52-aaec-da198d065295.jpg?im_w=1200',
        'description' => 'A spacious villa right by the lake, offering serene views and luxury amenities.',
        'num_rooms' => 6,
        'num_beds' => 6,
        'num_baths' => 4,
        'mq' => 280,
        'address' => 'Via Lago di Vico, 2, 01037 Ronciglione',
        'lat' => '42.328569',
        'long' => '12.216789',
        'price' => 1875.90,
        'type' => 'mansion',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Urban Studio with Balcony in Turin',
        'slug' => 'urban-studio-balcony-turin',
        'cover_image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-820896778503897920/original/bdd370e0-63fa-4852-a6f2-4c23a2f12356.jpeg?im_w=1200',
        'description' => 'A cozy studio apartment with a private balcony overlooking the vibrant city.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 45,
        'address' => 'Via Garibaldi, 3, 10121 Turin',
        'lat' => '45.070362',
        'long' => '7.686812',
        'price' => 720.50,
        'type' => 'apartment',
        'floor' => 4,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Seaside Apartment with Terrace in Palermo',
        'slug' => 'seaside-apartment-terrace-palermo',
        'cover_image' => 'https://a0.muscache.com/im/pictures/4de13a05-90d9-4c67-a4cb-0cf8dcbaf6f5.jpg?im_w=1200',
        'description' => 'A modern seaside apartment with a large terrace overlooking the ocean.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 75,
        'address' => 'Via del Mare, 7, 90143 Palermo',
        'lat' => '38.135689',
        'long' => '13.358978',
        'price' => 950.30,
        'type' => 'apartment',
        'floor' => 2,
        'available' => true,
        'sponsored' => false,
        'user_id' => 3
    ],
    [
        'title' => 'Charming Countryside Bungalow in Tuscany',
        'slug' => 'charming-countryside-bungalow-tuscany',
        'cover_image' => 'https://a0.muscache.com/im/pictures/8ef5797f-2fb8-4e82-96bd-d7e41dc3e25e.jpg?im_w=1200',
        'description' => 'A quaint bungalow in the rolling hills of Tuscany, perfect for relaxation.',
        'num_rooms' => 2,
        'num_beds' => 2,
        'num_baths' => 1,
        'mq' => 65,
        'address' => 'Via dei Cipressi, 14, 53013 Gaiole in Chianti',
        'lat' => '43.469891',
        'long' => '11.382012',
        'price' => 580.00,
        'type' => 'mansion',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ],
    [
        'title' => 'Historic Castle Tower in Sorano',
        'slug' => 'historic-castle-tower-sorano',
        'cover_image' => 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-786594155921786215/original/54545224-be32-4161-a4c5-72746e8ce418.jpeg?im_w=1200',
        'description' => 'A charming tower room within a historic castle, offering unique medieval charm.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 50,
        'address' => 'Castello di Sorano, 2, 58010 Sorano',
        'lat' => '42.683019',
        'long' => '11.722376',
        'price' => 385.75,
        'type' => 'castle',
        'floor' => 2,
        'available' => true,
        'sponsored' => false,
        'user_id' => 1
    ],
    [
        'title' => 'Spacious Treehouse with Mountain View in Bormio',
        'slug' => 'spacious-treehouse-mountain-view-bormio',
        'cover_image' => 'https://a0.muscache.com/im/pictures/b7e49a4c-12ce-4a51-ba52-0cd596843c02.jpg?im_w=1200',
        'description' => 'A beautiful treehouse with a large terrace and mountain views, ideal for adventurers.',
        'num_rooms' => 1,
        'num_beds' => 1,
        'num_baths' => 1,
        'mq' => 30,
        'address' => 'Strada del Bosco, 12, 23032 Bormio',
        'lat' => '46.469567',
        'long' => '10.368421',
        'price' => 295.50,
        'type' => 'tree-house',
        'floor' => 1,
        'available' => true,
        'sponsored' => false,
        'user_id' => 2
    ]
];
